# Site settings
title: Remembering Mandy Klyne
email: mandy.klyne.memorial@gmail.com
# baseurl: "" # Site hosted in top directory of specified host
baseurl: "/Mandy_Klyne_memorial" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Amanda (Mandy) Klyne 
description_2: 1955 - 2016

# Social icons
facebook: username
linkedin: username
github: username
deviantart: username
codepen: username

# footer: © Taken theme
footer: (footer)

# Build settings
markdown: kramdown
